### ISSUE TITLE
No Method Error: undefined method `start_with?' for :sleep:Symbol

### ISSUE THREAD

**Issue by santhu46** [ClayShentrup/method_man#9]
I'm getting above error after updating method man to 3.0.1, while using methods like **sleep, binding or if initiate a classes like Array**

```
NoMethodError: undefined method `start_with?' for :sleep:Symbol
  from method_man (3.0.1) lib/method_object.rb:120:in `name_matches?'
  from method_man (3.0.1) lib/method_object.rb:110:in `candidate?'
  from method_man (3.0.1) lib/method_object.rb:64:in `select'
  from method_man (3.0.1) lib/method_object.rb:64:in `candidates_for_method_missing'
  from method_man (3.0.1) lib/method_object.rb:38:in `respond_to_missing?
